### PR TITLE
Refactor some backend functions

### PR DESCRIPTION
**Pull request by Binary141**
Refactors some of the code that is used for scanning for movies and for some of the basic api routes

### CODE REVIEW

**Comment by kcpetersen111** [comment]
@Binary141 Do you want to use the go std lib for the http server or do you want to use a framework. In the past ive used gorilla mux but the whole web kit was deprecated, another possible choice is go gin but I have not used it before.  Or we could just stick with the std lib one if you would prefer.

**Comment by kcpetersen111** [comment]
Other than that conversation point LGTM

**Comment by Binary141** [comment]
I think the go std lib will be good enough for now, until we find a reason to change it at the moment. I think once we know more about the problems we are going to be facing

**Comment by kcpetersen111** [comment]
lgtm

**Review by kcpetersen111 — APPROVED** [review]

**Pull request merged**
